---
web1:
  hosts:
    mondskiez.com
  vars:
    ansible_user: morty
    ansible_private_key_file: ~/.ssh/ansible

web2:
  hosts:
    us.mondskiez.com
  vars:
    ansible_user: morty
    ansible_private_key_file: ~/.ssh/ansible

web3:
  hosts:
    unifi.mondskiez.com
  vars:
    ansible_user: morty
    ansible_private_key_file: ~/.ssh/ansible

web4:
  hosts:
    sfo3.mondskiez.com
  vars:
    ansible_user: morty
    ansible_private_key_file: ~/.ssh/ansible

web5:
  hosts:
    10.0.0.128
  vars:
    ansible_user: test-user
    ansible_ssh_private_key_file: ~/.ssh/ansible

web5b:
  hosts:
    192.168.8.128
  vars:
    ansible_user: morty
    ansible_ssh_private_key_file: /home/morty/.ssh/ansible

web6:
  hosts:
    192.168.8.128
  vars:
    ansible_user: test-user
    ansible_private_key_file: ~/.ssh/ansible

web6b:
  hosts:
    192.168.8.128
  vars:
    ansible_user: morty
    ansible_private_key_file: ~/.ssh/ansible

# test Ubuntu Server 24.04
web7:
  hosts:
    192.168.8.234
  vars:
    ansible_user: morty
    ansible_private_key_file: ~/.ssh/ansible
