---

- hosts: all
  become: true
  vars:
      desired_hostname: mondskiez-test
      tz: Asia/Manila
      user_name: morty
      user_home: /home/{{ user_name }}
      user_pword: $6$RWo0laTgZpiSlKES$X6adutPj3ZjVNubU3Ehg.E2B/DtEgd/ni7FGaa4XNVFdVrewPITM0fMUld5JD5hn8rrxXXnlvQBSeQ4uBBBfe0
      omz_install_path: "/home/{{ user_name }}/"
      omz_zsh_path: "/home/{{ user_name }}/.oh-my-zsh/"
      omz_auto_path: "/home/{{ user_name }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
      ssh_stream: 22
      port53systemd: systemd-r
      jammy: 22.04

  tasks:

### Base Server Defaults

### the following .yml files will be executed consecutively
### to disable a task simply comment out the line
  - include_tasks: playbooks/base-server/1-create-hostname.yml
  - include_tasks: playbooks/base-server/2-create-user.yml
  - include_tasks: playbooks/base-server/3-setup-apps.yml
  - include_tasks: playbooks/base-server/4-enable-ufw.yml
  - include_tasks: playbooks/base-server/5-secure-ssh.yml

### Server Maintenance

  - include_tasks: playbooks/server-maintenance/apt-upgrade.yml
  - include_tasks: playbooks/server-maintenance/livepatch.yml