---

### the hostname that you want the server to be
    - name: Set static hostname
      hostname:
        name: "{{ desired_hostname }}"

### adding a hostname entry to the host file in order for the server to be able to resolve itself
    - name: add hostname to /etc/hosts file
      lineinfile:
        dest: /etc/hosts
        state: present
        line: "127.0.0.1 {{ desired_hostname }}"
        insertafter: "EOF" 

### set your preferred timezone
    - name: Set Timezone
      timezone:
        name: "{{ tz }}"