---

### install your preferred base apps by listing them individually after name: -
    - name: Installing common base apps
      apt:
        update_cache: yes
        cache_valid_time: 3600
        name: "{{ item }}"
        state: present
      loop:
          - aptitude
          - bat
          - cron
          - curl
          - debconf
          - debconf-utils
          - fonts-powerline
          - fzf
          - git
          - haveged
          - htop
          - lsof
          - mc
          - micro
          - ncdu
          - net-tools
          - openssh-server
          - powerline
          - software-properties-common
          - sudo
          - tree
          - wget
          - whois
          - unattended-upgrades
          - ufw
          - zsh
          - zsh-syntax-highlighting

    - name: Ubuntu | installing distro-specific packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - awk
        - update-notifier-common
      when: ansible_distribution == "Ubuntu"

    - name: Debian | installing distro-specific packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-listchanges
        - gawk
      when: ansible_distribution == "Debian"
    
    - name: Ubuntu | removing snap
      apt:
        name:
          - snapd
        state: absent
      when: ansible_distribution == "Ubuntu"