---

### Enable SSH in UFW
    - name: UFW allow openssh
      ufw: 
        rule: allow
        name: OpenSSH

### UFW allow ports 80 and 443
    - name: UFW | add allow rules for ports 80 443 53
      ufw:
        rule: "{{ item.rule }}"
        port: "{{ item.port }}"
        proto: "{{ item.proto }}"
      loop:
        - rule: allow
          port: 80
          proto: tcp
        - rule: allow
          port: 443
          proto: tcp
        - rule: allow
          port: 53
          proto: tcp
        - rule: allow
          port: 53
          proto: udp

### enable and start UFW
    - name: UFW | enable and start service
      ufw:
        state: enabled