---

### check SSH port before changes are made thru grepping and awking of ss -tulpn
    - name: ssh | checking default port
      shell: 
        cmd: "sudo ss -tulpn | grep ssh | awk 'FNR == 1 {print $5}' | awk -F: '{print $2}'"
      register: ssh_port_before

### edit the sshd_config to configure sshkey login
    - name: ssh | modifying sshd_config file for publickey authentication only
      lineinfile: 
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - regexp: '^Include'
          line: '#Include /etc/ssh/sshd_config.d/*.conf'
        - regexp: '^#Port'
          line: 'Port {{ ssh_stream }}'
        - regexp: '^#?AuthenticationMethods' 
          line: 'AuthenticationMethods publickey'
        - regexp: '^#?PasswordAuthentication' 
          line: 'PasswordAuthentication no'
        - regexp: '^#?PubkeyAuthentication'
          line: 'PubkeyAuthentication yes'   
        - regexp: '^#PermitRootLogin'
          line: 'PermitRootLogin No'

    - name: ssh | creating ssh.socket.d directory
      file:
        dest: /etc/systemd/system/ssh.socket.d/
        state: directory
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
      when: (ansible_lsb.release|int >= 23 and ansible_distribution == "Ubuntu") or
            (ansible_lsb.release|int >= 10 and ansible_distribution == "Debian")

    - name: ssh | adding new SSH port via override.conf
      copy:
        dest: /etc/systemd/system/ssh.socket.d/override.conf
        content: |
          [Socket]
          ListenStream=
          ListenStream={{ ssh_stream }}
      when: (ansible_lsb.release|int >= 23 and ansible_distribution == "Ubuntu") or
            (ansible_lsb.release|int >= 10 and ansible_distribution == "Debian")

    - name: ssh | restarting service
      service:
        name: ssh.service
        state: restarted
      when: (ansible_lsb.release|int >= 23 and ansible_distribution == "Ubuntu") or
            (ansible_lsb.release|int >= 10 and ansible_distribution == "Debian")

    - name: ssh | restarting service
      service: 
        name: ssh
        state: restarted
      when: (ansible_lsb.release|int <= 22.05 and ansible_distribution == "Ubuntu") or
            (ansible_lsb.release|int < 10 and ansible_distribution == "Debian")
    
    - name: ufw | adding new SSH port
      ufw:
        rule: limit
        port: "{{ ssh_stream }}"
        proto: tcp

    - name: ufw | reloading service
      ufw:
        state: reloaded

    - name: ssh | checking new port number
      shell: 
        cmd: "sudo ss -tulpn | grep ssh | awk 'FNR == 1 {print $5}' | awk -F: '{print $2}'"
      register: ssh_port_after

    - name: ssh | comparing before and after ports
      debug:
        msg: 
        - "SSH port before: {{ ssh_port_before.stdout }}"
        - "SSH port after:  {{ ssh_port_after.stdout }}"
        - "----------------------------------------------------------------------------"
        - "Be sure to reconfigure your hosts.yml file to point to the new port at {{ ssh_port_after.stdout }}"