---

- hosts: all
  become: true
  tasks:

  - include_tasks: apt-update.yml
  - include_tasks: livepatch.yml
#  - include_tasks: 3-enable-ufw.yml
#  - include_tasks: 4-secure-ssh.yml
#  - include_tasks: reboot-server.yml