desired_hostname: mondskiez-test
tz: Asia/Manila
user_name: morty
user_home: /home/{{ user_name }}
user_pword: $6$RWo0laTgZpiSlKES$X6adutPj3ZjVNubU3Ehg.E2B/DtEgd/ni7FGaa4XNVFdVrewPITM0fMUld5JD5hn8rrxXXnlvQBSeQ4uBBBfe0
omz_install_path: "/home/{{ user_name }}/"
omz_zsh_path: "/home/{{ user_name }}/.oh-my-zsh/"
omz_auto_path: "/home/{{ user_name }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
ssh_stream: 22
port53systemd: systemd-r
cl_desired_time: 720
jammy: 22.04