---

### the base-server install starts from this play
### change the user morty to your desired username
- hosts: all
  become: true
  vars:
    desired_hostname: mondskiez-test
    tz: Asia/Manila
    user_name: morty
    user_home: /home/{{ user_name }}
    user_pword: $6$RWo0laTgZpiSlKES$X6adutPj3ZjVNubU3Ehg.E2B/DtEgd/ni7FGaa4XNVFdVrewPITM0fMUld5JD5hn8rrxXXnlvQBSeQ4uBBBfe0
    omz_install_path: "/home/{{ user_name }}/"
    omz_zsh_path: "/home/{{ user_name }}/.oh-my-zsh/"
    omz_auto_path: "/home/{{ user_name }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    ssh_stream: 22222
    port53systemd: systemd-r
    jammy: 22.04

  tasks:
### the following .yml files will be executed consecutively
### to disable a task simply put a # at the beginning of the task line
  - include_tasks: 1-create-hostname.yml
  - include_tasks: 2-create-user.yml
  - include_tasks: 3-setup-apps.yml
  - include_tasks: 4-enable-ufw.yml
  - include_tasks: 5-secure-ssh.yml