---

### install your preferred base apps by listing them individually after name: -
    - name: Installing base apps
      apt:
        update_cache: yes
        cache_valid_time: 3600
        name:
          - haveged
          - htop 
          - git
          - aptitude
          - net-tools
          - zsh
          - zsh-syntax-highlighting
          - powerline
          - fonts-powerline 
        state: latest

### this step is only for me coz I deploy docker Pi-Hole on all my servers
### by default Port 53 will be used by systemd
    - name: Check what is using Port 53
      shell:
        cmd: "sudo lsof -i:53 | awk 'FNR==2 {print $1}'"
      register: port53user

### show what process is using Port 53
    - name: What process is using Port 53?
      debug:
        msg: Port 53 is being used by "{{port53user.stdout}}"

### if Port 53 is being used by systemd then we have to free it up by editing resolved.conf
### this process will add DNS to 1.1.1.1 and DNSStubListener=no
    - name: editing /etc/systemd/resolved.conf
      lineinfile:
        path: /etc/systemd/resolved.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - regexp: '^#DNS='
          line: 'DNS=1.1.1.1'
        - regexp: '^#DNSStubListener=yes'
          line: 'DNSStubListener=no'
      when: port53user.stdout == port53systemd

### if Port 53 is being used by systemd then we have to force remove the existing symbolic links
### this will only take effect after a server reboot
    - name: Removing existing symbolic link of resolv.conf
      command: sudo ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf
      when: port53user.stdout == port53systemd

### since I prefer using ZSH to bash
    - name: change morty default shell to ZSH
      command: usermod -s /usr/bin/zsh morty

### setting the fact for user home directory
    - name: Establish user %HOME directory
      set_fact:
        omz_user_home_dir: "{{ user_home }}"

### setting the fact for OMZ install location
    - name: Establish Oh-My-ZSH install directory
      set_fact:
        omz_install_path: "{{ user_home }}.oh-my-zsh"

### checking user %HOME director for .oh-my-zsh sub-directory
    - name: check if .oh-my-zsh folder exists in %HOME
      stat:
        path: "{{ user_home }}.oh-my-zsh"
      register: omz_folder_present

### this part is crucial because if the folder exists, the next task will not run
### however if the folder does not exist, then the we clone the Oh-My-ZSH git repo
    - name: Show results omz folder exists
      debug:
        msg: "folder exists at {{ user_home }}.oh-my-zsh"
      when: omz_folder_present.isdir is defined and omz_folder_present.stat.isdir

### git clone the Oh-My-ZSH repo if folder above does not exist
    - name: Cloning Oh-My-ZSH repo for user
      git:
        repo: "https://github.com/robbyrussell/oh-my-zsh.git"
        dest: "{{ user_home }}.oh-my-zsh"
        update: "true"
        accept_hostkey: "true"
        version: "master"
      when: omz_folder_present.isdir is false

### checking user %HOME directory for zsh-autosuggestion directory under plugins subdirectory of OMZ
    - name: check if zsh-autosuggestion folder exists
      stat:
        path: "{{ user_home }}.oh-my-zsh/custom/plugins/zsh-autosuggestions"
      register: zsh_auto_present

### crucial part again, if zsh-autosuggestion folder exists, above the next task is skipped
### however, if the zsh-autosuggestion folder does not exist, the we git clone the repo
    - name: "zsh-autosuggestions folder exists"
      debug:
        msg: "zsh-autosuggestions folder exists"
      when: zsh_auto_present.isdir is defined and zsh_auto_present.stat.isdir

### git clone the zsh-autosuggestions repo if folder above does not exist
    - name: "Git clone zsh-autosuggestions repo"
      git:
        repo: "https://github.com/zsh-users/zsh-autosuggestions"
        dest: "{{ user_home }}.oh-my-zsh/custom/plugins/zsh-autosuggestions"
        update: "true"
        accept_hostkey: "true"
        version: "master"
      when: zsh_auto_present.isdir is false
### change owner and group of .oh-my-zsh folder to morty
    - name: "Set ownership on .oh-my-zsh folder to."
      file:
        path: "{{ user_home }}.oh-my-zsh"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        recurse: "true"

### creating an empty hidden .hushlogin to disable Ubuntu message-of-the-day
    - name: create .hushlogin file to disable MOTD
      command: touch ~/.hushlogin

### creating my desired .zshrc file with my preferred theme, plugins and aliases already incorporated
    - name: "Creating a .zshrc file"
      copy:
        dest: "{{ user_home }}/.zshrc"
        content: |
          ZSH_THEME="xiong-chiamiov-plus"
          plugins=(git sudo colored-man-pages zsh-autosuggestions)
          source /home/morty/.oh-my-zsh/oh-my-zsh.sh
          source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
          export PATH="/home/morty/.local/bin:$PATH"%
          alias tq="clear && /usr/bin/bash /home/morty/tq.sh"
          alias tp="clear && /usr/bin/bash /home/morty/tp.sh"
          alias update="clear && sudo apt-get update -y && sudo apt-get upgrade -y && sudo apt-get dist-upgrade -y && sudo apt autoclean -y && sudo apt autoremove -y"
          alias f2bss="sudo docker exec -it fail2ban fail2ban-client status sshd"
          alias f2br="sudo docker exec -it fail2ban fail2ban-client restart"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
  
  ### source the .zshrc file above for changes to take effect
    - name: Run source to .zshrc to effect changes
      shell: /usr/bin/zsh "{{ user_home }}"/.zshrc