---

### Enable SSH in UFW
    - name: UFW allow openssh
      ufw: 
        rule: allow
        name: OpenSSH

### UFW allow ports 80 and 443
    - name: UFW allow ports 80 443
      ufw:
        rule: "{{ item.rule }}"
        port: "{{ item.port }}"
        proto: "{{ item.proto }}"
      loop:
        - rule: allow
          port: 80
          proto: tcp
        - rule: allow
          port: 443
          proto: tcp

### enable and start UFW
    - name: enable and start UFW service
      ufw:
        state: enabled