---

### check SSH port before changes are made thru grepping and awking of ss -tulpn
    - name: "checking default SSH port"
      shell: 
        cmd: "sudo ss -tulpn | grep ssh | awk 'FNR == 1 {print $5}' | awk -F: '{print $2}'"
      register: ssh_port_before

### edit the sshd_config to configure sshkey login
    - name: modifying sshd_config for sshkey login only
      lineinfile: 
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - regexp: '^Include'
          line: '#Include /etc/ssh/sshd_config.d/*.conf'
        - regexp: '^#Port'
          line: 'Port 22222'
        - regexp: '^#?AuthenticationMethods' 
          line: 'AuthenticationMethods publickey'
        - regexp: '^#?PasswordAuthentication' 
          line: 'PasswordAuthentication no'
        - regexp: '^#?PubkeyAuthentication'
          line: 'PubkeyAuthentication yes'   
        - regexp: '^#PermitRootLogin'
          line: 'PermitRootLogin No'

### on Ubuntu distros above 22.04 ssh is being handled by ssh.socket
### in order to save changes to the sshd_config, a directory must first be created
    - name: creating ssh.socket.d directory on distros above 22.04
      file:
        dest: /etc/systemd/system/ssh.socket.d/
        state: directory
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
      when: ansible_lsb.release|int >= 22.05

### after task above runs, an override.conf file must be created
### the override.conf file incorporates the variable for {{ ssh_stream }} as desired SSH port
    - name: creating override.conf on distros above 22.04 for desired SSH port 
      copy:
        dest: /etc/systemd/system/ssh.socket.d/override.conf
        content: |
          [Socket]
          ListenStream=
          ListenStream={{ ssh_stream }}
      when: ansible_lsb.release|int >= 22.05

### the ansible_lsb.release variable is piped into integer and is compared if it is less than or equal to 22.04
### for 22.04 means it is Ubuntu Jammy Release
    - name: Enabling SSH service on distros <= 22.04
      command: sudo systemctl enable ssh
      when: ansible_lsb.release|int <= 22.04

### the ansible_lsb.release variable is piped into integer and is compared if it is greater than or equal to 22.05
### 22.05 means it is above the Ubuntu Jammy Release 
    - name: Enabling SSH service on distros > 22.04
      command: sudo systemctl enable ssh.service
      when: ansible_lsb.release|int >= 22.05

### Jammy distro and below
    - name: Restarting SSH service on distros <= 22.04
      command: sudo systemctl restart ssh
      when: ansible_lsb.release|int <= 22.04

### Distro is greater than Jammy
    - name: Restarting SSH service on distros > 22.04
      command: sudo systemctl restart ssh.service
      when: ansible_lsb.release|int >= 22.05

    - name: UFW limit new SSH port
      ufw:
        rule: limit
        port: "{{ ssh_stream }}"
        proto: tcp
    
    - name: Reloading UFW service
      command: sudo ufw reload

    - name: Checking process user for new SSH port
      shell: 
        cmd: "sudo ss -tulpn | grep ssh | awk 'FNR == 1 {print $5}' | awk -F: '{print $2}'"
      register: ssh_port_after

    - name: "Comparing SSH ports before and after"
      debug:
        msg: 
        - "SSH port before is {{ ssh_port_before.stdout }}"
        - "SSH port after is {{ ssh_port_after.stdout }}"
        - "----------------------------------------------------------------------------"
        - "Be sure to reconfigure your hosts.yml file to point to the new port at {{ ssh_port_after.stdout }}"