---

### check SSH port before changes are made via grepping and awking ss -tulpn
    - name: "check default SSH port"
      shell: 
        cmd: "sudo ss -tulpn | grep ssh | awk 'FNR == 1 {print $5}' | awk -F: '{print $2}'"
      register: ssh_port_before

### show the return value of default SSH port
    - name: SSH default port
      debug:
        msg: "SSH default port is {{ ssh_port_before.stdout }}"

### edit the sshd_config to configure pubkeyauth only
    - name: modifying sshd_config for pubkeyauth only
      lineinfile: 
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - regexp: '^Include'
          line: '#Include /etc/ssh/sshd_config.d/*.conf'
        - regexp: '^#Port'
          line: 'Port 22222'
        - regexp: '^#?AuthenticationMethods' 
          line: 'AuthenticationMethods publickey'
        - regexp: '^#?PasswordAuthentication' 
          line: 'PasswordAuthentication no'
        - regexp: '^#?PubkeyAuthentication'
          line: 'PubkeyAuthentication yes'   
        - regexp: '^#PermitRootLogin'
          line: 'PermitRootLogin No'

### on Ubuntu distros above 22.04 ssh is being handled by ssh.socket
### in order to save changes to the sshd_config, a directory must first be created
    - name: creating ssh.socket.d directory
      file:
        dest: /etc/systemd/system/ssh.socket.d/
        state: directory
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
      when: ansible_lsb.release|int >= 22.05

### after task above, an overried.conf file must be created
### the file incorporates the ssh_stream var to ListenStream=ssh_stream
    - name: "creating override.conf to specify SSH port Ubuntu Server 22.10 and higher"
      copy:
        dest: /etc/systemd/system/ssh.socket.d/override.conf
        content: |
          [Socket]
          ListenStream=
          ListenStream={{ ssh_stream }}
      when: ansible_lsb.release|int >= 22.05

    - name: Enabling SSH service on distros <= 22.04
      command: sudo systemctl enable ssh
      when: ansible_lsb.release|int <= 22.04
    
    - name: Enabling SSH service on distros > 22.04
      command: sudo systemctl enable ssh.service
      when: ansible_lsb.release|int >= 22.05

    - name: Restarting SSH service on distros <= 22.04
      command: sudo systemctl restart ssh
      when: ansible_lsb.release|int <= 22.04

    - name: Restarting SSH service on distros > 22.04
      command: sudo systemctl restart ssh.service
      when: ansible_lsb.release|int >= 22.05

    - name: UFW allow new ssh port
      ufw:
        rule: limit
        port: "{{ ssh_stream }}"
        proto: tcp
    
    - name: Reload UFW service
      command: sudo ufw reload

    - name: check new ports results
      shell: 
        cmd: "sudo ss -tulpn | grep ssh | awk 'FNR == 1 {print $5}' | awk -F: '{print $2}'"
      register: ssh_port_after

    - name: "SSH port before and after comparison"
      debug:
        msg: 
        - "SSH port before is {{ ssh_port_before.stdout }}"
        - "SSH port after is {{ ssh_port_after.stdout }}"