---

- hosts: all
  become: yes
  tasks:
    - name: creating ~/docker/fail2ban directory
      file:
        dest: ~/docker/fail2ban/
        state: directory
        mode: '0755'

    - name: copying fail2ban compose file
      copy:
        src: fail2ban/docker-compose.yml
        dest: ~/docker/fail2ban
        owner: morty
        group: morty
        mode: '0755'

    - name: deploying fail2ban
      community.docker.docker_compose_v2:
        project_src: ~/docker/fail2ban/
        files:
        - docker-compose.yml
        state: present

    - name: creating jail.local
      copy:
        src: fail2ban/jail.local
        dest: ~/docker/fail2ban/data/jail.d/
        owner: morty
        group: morty
        mode: '0755'
    
    - name: restarting fail2ban
      community.docker.docker_compose_v2: 
        project_src: ~/docker/fail2ban/
        state: restarted