services:
  nginx-proxy-manager:
    image: 'lepresidente/nginx-proxy-manager:latest'
    restart: always
    ports:
      - "8181:8181"
      - "80:8080"
      - "443:4443"
    environment:
      TZ: "Asia/Manila"
      DISABLE_IPV6: "1"
    volumes:
      - "/home/morty/npm/data/nginx-proxy-manager:/config:rw"
      - "/home/morty/npm/data/nginx-proxy-manager/crowdsec/templates:/templates:ro"
    networks:
      crowdsec_proxy:
        ipv4_address: 172.20.0.4

  crowdsec:
    image: "crowdsecurity/crowdsec:latest"
    container_name: crowdsec
    expose:
      - 8080
    environment:
      PGID: "1000"
      COLLECTIONS: "crowdsecurity/http-cve crowdsecurity/whitelist-good-actors crowdsecurity/iptables crowdsecurity/nginx crowdsecurity/nginx-proxy-manager"
    volumes:
      - "/home/morty/npm/crowdsec/data:/var/lib/crowdsec/data"
      - "/home/morty/npm/crowdsec/config:/etc/crowdsec"
      - "/var/log/auth.log:/var/log/auth.log:ro"
      - "/data/logs:/var/log/nginx:ro"
    restart: unless-stopped
    networks:
      crowdsec_proxy:
        ipv4_address: 172.20.0.6

networks:
  crowdsec_proxy:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24