---

    - name: create ~/docker/portainer directory
      file:
        dest: ~/docker/portainer/
        state: directory
        mode: '0755'

    - name: copying pihole compose file
      copy:
        src: portainer/docker-compose.yml
        dest: ~/docker/pihole/
        owner: morty
        group: morty
        mode: '0755'

    - name: deploying pihole
      community.docker.docker_compose_v2:
        project_src: ~/docker/portainer/
        files:
        - docker-compose.yml
        state: present
