---

- hosts: all
  become: true
  tasks:

    - name: "modifying sshd_config"
      lineinfile: 
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - regexp: '^#?AuthenticationMethods' 
          line: 'AuthenticationMethods publickey'
        - regexp: '^#?PasswordAuthentication' 
          line: 'PasswordAuthentication no'
        - regexp: '^#?PubkeyAuthentication'
          line: 'PubkeyAuthentication yes'   
        - regexp: '^#PermitRootLogin'
          line: 'PermitRootLogin No'
    
    - name: "Restart SSH server"
      command: sudo systemctl restart ssh