services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest # <- update image version here, see: https://github.com/pi-hole/docker-pi-hole/releases
    hostname: pihole
    depends_on:
      - unbound
    restart: unless-stopped
    ports:
      - "8081:80/tcp" # web ui -> http://localhost:8080/admin
      - "53:53/tcp" # DNS tcp port is used as fallback for longer dns messages
      - "53:53/udp" # DNS port
# RECOMMENDED: Uncomment and adapt if you want to persist pihole configurations after restart
    volumes:
      - "~/docker/pihole/pihole:/etc/pihole/"
      - "~/docker/pihole/dnsmasq.d:/etc/dnsmasq.d/"
    environment:
      WEBPASSWORD: 'authy backups are so great'
      TZ: 'Asia/Manila'
      PIHOLE_DNS_: 172.25.80.3#53 # forward to unbound
      # DNSSEC: true
      # WEBTHEME: default-dark
    dns:
      - 127.0.0.1
      - 9.9.9.9 # Quad9
      - 1.1.1.1 # CloudFlare
    networks:
      pihole_dns_network:
        ipv4_address: 172.25.80.2 # <-- use this ip as dns when connected to pihole_dns_network (i.e. within a docker network)
  unbound:
    image: mvance/unbound:latest
    container_name: unbound
    hostname: unbound.local
    restart: unless-stopped
    ports:
      - "5335:53/tcp" # expose a different port (5335) so you can use it directly
      - "5335:53/udp"
    networks:
      pihole_dns_network:
        ipv4_address: 172.25.80.3 # <-- this is used by pihole as upstream DNS

networks:
  # Define a custom subnet for pihole so that unbound can be an upstream DNS on port 53
  pihole_dns_network:
    name: "pihole_dns_network"
    ipam:
      driver: default
      config:
        - subnet: 172.25.80.0/24
          gateway: 172.25.80.1
          ip_range: 172.25.80.0/24 # 172.21.200.1 - 172.21.200.254