volumes:
  etc_wireguard:

services:
  wg-easy:
    environment:
      - LANG=en
      - WG_HOST=us.mondskiez.com
      - PASSWORD=authy backups are so great
      - WG_DEFAULT_ADDRESS=10.19.80.x
      - WG_DEFAULT_DNS=128.199.129.159, 188.166.230.62, 159.65.111.187, 144.126.213.78
      - WG_ALLOWED_IPS=0.0.0.0/1, 128.0.0.0/1, 10.0.0.0/24, 192.168.1.0/24, 192.168.8.0/24
      - WG_PERSISTENT_KEEPALIVE=25
      - UI_TRAFFIC_STATS=true
      - UI_CHART_TYPE=3
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - ~/docker/wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1